News bootstrap
jaimdedan/newsweek_bootstrap pull request #1
Opened 2020-12-09 22:21 UTC by jaimdedan

This is a project of cloning Newsweek's webpage. We used the mobile-first philosophy and we created two breakpoints for tablet and desktop.
For this project, we decided to use Sass as a preprocessor to help us with color variables and mixins for different elements. And also we used bootstrap to help us style the project.

2020-12-09 22:58 UTC, arslanbisharat requested changes
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [x] Please remove linter errors. Always check if there is an error before submitting a review request. 
<img width="485" alt="10" src="https://user-images.githubusercontent.com/58504655/101699193-8e33ca00-3a9c-11eb-92da-b16cdb5a9552.PNG">

- [x] Please don't leave **alt** and **href** attributes empty. This is not a good practice. 
- [x] You have used too much CSS although the purpose of this project is to show your bootstrap skills. Please work on the changes and change CSS to bootstrap. 
- [x] Please add CSS, SCSS, and assets folders into a single folder. 
<img width="269" alt="11" src="https://user-images.githubusercontent.com/58504655/101699703-74df4d80-3a9d-11eb-9a30-6ef33ee6e04f.PNG">

- [x] On the desktop version of your webpage the login and Subscribe button lacks proper stylings. Please work on them. 

**Yours Clone**
<img width="152" alt="12 1" src="https://user-images.githubusercontent.com/58504655/101699925-f9ca6700-3a9d-11eb-9ecb-3eff486d395d.PNG">

**Original**

<img width="188" alt="12 2" src="https://user-images.githubusercontent.com/58504655/101699952-051d9280-3a9e-11eb-9cc6-11d2b728e047.PNG">

- [x] The debate section is almost similar to the original one. But a few modifications required. 

**Clone**

<img width="237" alt="13 1" src="https://user-images.githubusercontent.com/58504655/101700109-4d3cb500-3a9e-11eb-824c-1ec4e2757fdf.PNG">

**Original**

<img width="271" alt="13 2" src="https://user-images.githubusercontent.com/58504655/101700131-562d8680-3a9e-11eb-9716-332a476cd2d9.PNG">

- [x] Please decrease the font-size for OPINION Section. 

- [ ] Please remove these empty spaces
1- 
<img width="922" alt="14 1" src="https://user-images.githubusercontent.com/58504655/101700389-c3411c00-3a9e-11eb-947f-55dc8aaa81cd.PNG">

2- 
<img width="939" alt="14 2" src="https://user-images.githubusercontent.com/58504655/101700421-d05e0b00-3a9e-11eb-844c-7601418d9b0d.PNG">

- [x] Please remove the white space from IN `THE MAGAZINE` section. 

**Clone**

<img width="949" alt="15 1" src="https://user-images.githubusercontent.com/58504655/101700632-35196580-3a9f-11eb-92b5-8a6011f04f7d.PNG">

**Original**

<img width="934" alt="15 2" src="https://user-images.githubusercontent.com/58504655/101700671-45314500-3a9f-11eb-9dbc-aaec8d6a817e.PNG">

- [x] Please decrease the white space from this section 
<img width="1012" alt="16" src="https://user-images.githubusercontent.com/58504655/101700762-701b9900-3a9f-11eb-85c1-f22ab8baf68c.PNG">

- [x] Please make these changes from the footer section

**Clone**

<img width="931" alt="17" src="https://user-images.githubusercontent.com/58504655/101700969-d1dc0300-3a9f-11eb-9c57-60b32f788e96.PNG">

**Original**

<img width="951" alt="17 1" src="https://user-images.githubusercontent.com/58504655/101700989-dc969800-3a9f-11eb-9231-24b2bd49a909.PNG">



**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach me out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-12-09 23:28 UTC, arslanbisharat requested changes

2020-12-09 23:28 UTC, arslanbisharat commented on css/style.css
> +    text-align: left !important;
- [ ] Please remove important

2020-12-10 23:01 UTC, arslanbisharat requested changes
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [x] Please decrease the font-size for OPINION Section.

- [ ] Please remove these empty spaces from the area described in the previous review.

- [ ] Please remove the white space from `IN THE MAGAZINE` section.

- [x] YOUR CLONE IS MISSING MANY SECTIONS. PLEASE WORK ON THEM. I AM SORRY I MISSED THOSE IN MY PREVIOUS REVIEW. 

- [ ] Newsweek logo in footer is too much big


**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach me out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-12-11 01:26 UTC, jaimdedan commented
Fixed all the observations. Thanks a lot for your time.

2020-12-11 01:44 UTC, descholar-ceo commented
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

2020-12-11 02:11 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @jpdf00 and @jaimdedan  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Add this project name in your readme file, currently the title says `Project Name` :point_right: this is irrelavant
- [x] The Top stories should be at the top in mobile screens, currently at the top there is Featured stories, please fix that
- [x] Fix the subscribe section on both desktop screens and tablet screens (large and medium screens). Learn the screenshots below

| Your clone | Original page |
| --- | --- |
|![Screenshot from 2020-12-11 04-08-02](https://user-images.githubusercontent.com/56886064/101852526-850f2f80-3b66-11eb-9789-a40cad81b2d8.png)|![Screenshot from 2020-12-11 04-08-48](https://user-images.githubusercontent.com/56886064/101852551-97896900-3b66-11eb-94b3-351090cba6c0.png)|

:point_right: Could you see the difference :question: :question: :question: 

- [x] You are missing vertical line after each link in the footer, and some spacing to make it look like the original. Fix them as well.
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2020-12-11 04:21 UTC, mimipeshy commented
## STATUS : APPROVED 🥳 🍾 

Hello team @jaimdedan and @jpdf00, congratulations your project is approved! Go ahead and merge. All the best in the next project 😄 

Happy coding!

Regards
Peris Ndanu

2020-12-11 13:56 UTC, merged